[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", default-features = false, features = ["rwh_05"] }
shipyard = "0.6.2"
wgpu = "0.18.0"
crossbeam-queue = "0.3.11"
raw-window-handle = "0.5.2"
futures-lite = "2.2.0"